# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  db:
      class: AppBundle\Database\DatabaseConnection
  app.form.type.category:
      class: AppBundle\Form\Type\CategoryType
      tags:
          - { name: form.type }
  traits.referer:
      class: AppBundle\Traits\Referer
